"""
constants.py — 모든 TagID의 단일 진실 소스 (Single Source of Truth)
기준: 한글문서파일형식_5.0_revision1.3.pdf
"""

HWPTAG_BEGIN = 16  # 0x010

# ──── DocInfo 레코드 (스펙 표 13) ────
HWPTAG_DOCUMENT_PROPERTIES  = 16   # BEGIN+0
HWPTAG_ID_MAPPINGS          = 17   # BEGIN+1
HWPTAG_BIN_DATA             = 18   # BEGIN+2
HWPTAG_FACE_NAME            = 19   # BEGIN+3
HWPTAG_BORDER_FILL          = 20   # BEGIN+4
HWPTAG_CHAR_SHAPE           = 21   # BEGIN+5
HWPTAG_TAB_DEF              = 22   # BEGIN+6
HWPTAG_NUMBERING            = 23   # BEGIN+7
HWPTAG_BULLET               = 24   # BEGIN+8
HWPTAG_PARA_SHAPE           = 25   # BEGIN+9
HWPTAG_STYLE                = 26   # BEGIN+10
HWPTAG_DOC_DATA             = 27   # BEGIN+11
HWPTAG_DISTRIBUTE_DOC_DATA  = 28   # BEGIN+12
HWPTAG_COMPATIBLE_DOCUMENT  = 30   # BEGIN+14
HWPTAG_LAYOUT_COMPATIBILITY = 31   # BEGIN+15

# ──── BodyText 레코드 (스펙 표 57) ────
HWPTAG_PARA_HEADER      = 66   # BEGIN+50
HWPTAG_PARA_TEXT        = 67   # BEGIN+51
HWPTAG_PARA_CHAR_SHAPE  = 68   # BEGIN+52
HWPTAG_PARA_LINE_SEG    = 69   # BEGIN+53
HWPTAG_PARA_RANGE_TAG   = 70   # BEGIN+54
HWPTAG_CTRL_HEADER      = 71   # BEGIN+55
HWPTAG_LIST_HEADER      = 72   # BEGIN+56
HWPTAG_PAGE_DEF         = 73   # BEGIN+57
HWPTAG_FOOTNOTE_SHAPE   = 74   # BEGIN+58
HWPTAG_PAGE_BORDER_FILL = 75   # BEGIN+59
HWPTAG_SHAPE_COMPONENT  = 76   # BEGIN+60
HWPTAG_TABLE            = 77   # BEGIN+61
HWPTAG_SHAPE_COMP_LINE      = 78   # BEGIN+62
HWPTAG_SHAPE_COMP_RECT      = 79   # BEGIN+63
HWPTAG_SHAPE_COMP_ELLIPSE   = 80   # BEGIN+64
HWPTAG_SHAPE_COMP_ARC       = 81   # BEGIN+65
HWPTAG_SHAPE_COMP_POLYGON   = 82   # BEGIN+66
HWPTAG_SHAPE_COMP_CURVE     = 83   # BEGIN+67
HWPTAG_SHAPE_COMP_OLE       = 84   # BEGIN+68
HWPTAG_SHAPE_COMP_PICTURE   = 85   # BEGIN+69
HWPTAG_SHAPE_COMP_CONTAINER = 86   # BEGIN+70
HWPTAG_CTRL_DATA        = 87   # BEGIN+71
HWPTAG_EQEDIT           = 88   # BEGIN+72
HWPTAG_SHAPE_COMP_TEXTART   = 90   # BEGIN+74
HWPTAG_FORM_OBJECT      = 91   # BEGIN+75
HWPTAG_MEMO_SHAPE       = 92   # BEGIN+76
HWPTAG_MEMO_LIST        = 93   # BEGIN+77
HWPTAG_CHART_DATA       = 95   # BEGIN+79
HWPTAG_VIDEO_DATA       = 98   # BEGIN+82
