# Adobe Core 14 AFM metrics and Adobe Glyph List
#
# Copyright (c) 1985, 1987, 1988, 1989, 1997 Adobe Systems Incorporated. All Rights Reserved.
# Copyright (c) 1985, 1987, 1988, 1989, 1997 Adobe Systems Incorporated. All Rights Reserved.ITC Zapf Dingbats is a registered trademark of International Typeface Corporation.
# Copyright (c) 1985, 1987, 1989, 1990, 1993, 1997 Adobe Systems Incorporated.  All Rights Reserved.
# Copyright (c) 1985, 1987, 1989, 1990, 1993, 1997 Adobe Systems Incorporated.  All Rights Reserved.Times is a trademark of Linotype-Hell AG and/or its subsidiaries.
# Copyright (c) 1985, 1987, 1989, 1990, 1997 Adobe Systems Incorporated.  All Rights Reserved.
# Copyright (c) 1985, 1987, 1989, 1990, 1997 Adobe Systems Incorporated.  All Rights Reserved.Helvetica is a trademark of Linotype-Hell AG and/or its subsidiaries.
# Copyright (c) 1985, 1987, 1989, 1990, 1997 Adobe Systems Incorporated. All rights reserved.
# Copyright (c) 1989, 1990, 1991, 1992, 1993, 1997 Adobe Systems Incorporated.  All Rights Reserved.
# Copyright (c) 1989, 1990, 1991, 1993, 1997 Adobe Systems Incorporated.  All Rights Reserved.
#
# This file and the 14 PostScript(R) AFM files it accompanies may be used, copied, and distributed for any purpose and without charge, with or without modification, provided that all copyright notices are retained; that the AFM files are not distributed without this file; that all modifications to this file or any of the AFM files are prominently noted in the modified file(s); and that this paragraph is not modified. Adobe Systems has no responsibility or obligation to support the use of the AFM files.
#
# Modified: dochan extracts only glyph names, advance widths (WX) and built-in encoding codes from the AFM files, adds a Unicode mapping using the Adobe Glyph List, and rebuilds the WinAnsi and MacRoman tables from Python codecs. The original AFM files are not distributed with dochan.
# (AFM 에서 글리프 이름·폭·내장 인코딩 코드만 추출하고 Adobe Glyph List 로 유니코드 대응표를 더한 수정본이며, 원본 AFM 은 배포하지 않습니다.)
#
# Copyright 2002-2019 Adobe (http://www.adobe.com/).
#
# Redistribution and use in source and binary forms, with or
# without modification, are permitted provided that the
# following conditions are met:
#
# Redistributions of source code must retain the above
# copyright notice, this list of conditions and the following
# disclaimer.
#
# Redistributions in binary form must reproduce the above
# copyright notice, this list of conditions and the following
# disclaimer in the documentation and/or other materials
# provided with the distribution.
#
# Neither the name of Adobe nor the names of its contributors
# may be used to endorse or promote products derived from this
# software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
# CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
# INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR
# CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
# NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
# OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# FontTools ZapfDingbats Unicode mapping (Adobe ITC Zapf Dingbats Glyph List, BSD-3, via fontTools):
#
# MIT License
#
# Copyright (c) 2017 Just van Rossum
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

"""Generated by scripts/generate_pdf_core14.py; do not edit by hand."""
import base64
import json
import zlib

SOURCE_SHA256 = {'Courier-Bold.afm': '1e86f0a949e316c08df32adc2fc2e2a92ed9902ffd54e3516e5a66a32db856da', 'Courier-BoldOblique.afm': 'e1349f5f306b16338972eaf7f43d7913535cc075a15189b5f3efc841aee3d02e', 'Courier-Oblique.afm': '9e3494b4abb127a6586c095a377924514dd6956973f8f3b0bd7d6d00fcc89ea6', 'Courier.afm': 'e72833dda79161e3aaf385adfeb59c61c89a4a3e184f27d21c178056eea30e17', 'Helvetica-Bold.afm': '59ac93091bc7e76eb6baf60210526a4df88fe107dd5e13eb0ae70c9fc6d91fb9', 'Helvetica-BoldOblique.afm': '1f848276efd76c0e5020ef98ccb459005f5a022f56cb8579e52c98e33ffab03b', 'Helvetica-Oblique.afm': '8c00ac46ca5963df22d4fc1153ea1246c8778475820378640c8d54d4fd3a46fe', 'Helvetica.afm': '5654761eab868ccb3080122accf13b4fb79edf37af09e1c57a881c35c334ee03', 'Symbol.afm': '13eeef80def2f9a8d3a31a980731376823e8b48340ff3891ffc1cc0299c0b4fe', 'Times-Bold.afm': '37efa084183acfb06f45ad73bd75f6dd09b20d1e498c66ce1b9aa72b00db4ac7', 'Times-BoldItalic.afm': '1bf83cee5300d4de1ce90681a2a2d70fd1876c664e91c1c4c6b6b5b12873b6da', 'Times-Italic.afm': '2f34d3bc49530532daa690aec165b68368162d4c27d24fbe6a3fb24aae49a74a', 'Times-Roman.afm': 'b6dbde33196ff61f051f8468fb81a0dece63997a80b7fba058e8295f49480026', 'ZapfDingbats.afm': 'd3e7b9f6366ab0df06acbb217c8586c5962ff2efbd4e1b5566c7eaf5b745dd41'}

_DATA = (
    'c-rlK3wInhvff`wn0K-_nSOUOPg>@Bxt2vQDXuN$CN~&PlbqFXhC2_*)W-Sk>H4Y)D0B}gS(a^i-ACtWP}SW)p#T)BK0NrhgLZkj'
    'n$4Hjn}fr@9em|3&sMi?c`QugW$D4;!RF3gwg<mE$g+-Tzq?$xTcYxg`s;4BZD-R3(M3lucem4ay_sJxiBoo**=n(HYoe--x@*^$'
    '?Q%<G-I4CLV{F`VMvO-D+jNC5sK9(epSX3qT(np8QJyGcJ-@yIhXiz+ZM&XtUJ*?)-Ys?;N|S__tJ_;g1c`TZe|OW8XnD!P%vV%&'
    'PNHoVZgWEf3HG*KuP9A2t(GK9L9%S$5Vs&Hwm0h*d=lVlwWBH)RQT2WHTYEcX8s)|spw7n8YLH0ax2moRPb`n1=NssvBFyoKDnJM'
    'qom>&?S|@AQu*y)caGFvQu){G)^#c%GJ_V|&34Y;kr<B3DoKhXN{|GfQG!Z;LJ2DRb4pOL$6cbL;(kvFD(eeMP&t2~1eI_?3CjA9'
    'l%Slyqy**sloFKlSCpWfpHYHxKJ5}U<@_}zDCa*>f^t5i1m%2A3Cj67B`D_$N>I*!rUd2u4J9b&Zz(}JzvvPT<@}Nol=F1$E?>1<'
    '={OCQG3_|o%1svD(Z19`SDVZE{Bpj&+)*cQNPyjP*7efM)tZ{ADWPwNMs7$N>Rk;<Go=JcbJ-=535hd93hjjyItx-%{xwom>J3s<'
    '*c>S;<S$5339pc%A{Izd86;hjP#H_4sEid-RK^`r=nF_u8Ed4_7m=bewn$MKJEW+L*GN$rZzz>g8Q&pAW!xi0WxPd7_1KE0lQf5_'
    'QCeE)Q`K>jma63Kd@+MoQY!UmHgDJ6(1&a(m437)Bh*nDN$}*doy|K_0tN|k>@Ig(d=De_%x4EPb!xMNsk(?bB$x|1Kqzh11g6Sy'
    'C%9U)s65-ND31n1ON)iEaw;<{)uoXchN|@?!cMimM3|~JE)f>1wI#x8%|jj}<~-y<63%;hkc@Mi2kh9=OATAL@>#-~t$da+Xsb9&'
    '7`9cEB?-C;S(22ykR^Io$daVo^|B->cQ#9yyP3PbhEYpk@n)U6U~&`KJefxlSUj2l7NUBXyiI#47BGR~o9-5imftUV4x#40!?=ST'
    '>`Ln9zHTbx@=3~ddp)O&Ta04Z#>>^+z3<8}lH0YLwYP4KF$!zxYYvlXYXysWbc`ekb*k1Vfx)C{>vq1x+?Bvi-eby0U@C7hLSg?_'
    '>)BN|H^{`1z!Y}8+iqCx7Q%!zbeu#R`?6pQb&8m+-k^vk%<Y~<(k@ol^Gml_u25qbzpKTn>*XLxCD*&Ii?_EcHMJ=WpXaK!QnrGN'
    '#r%%7kxr~{k-{JzX*Wq>6_2z}r7(@Bfh0LjkCB8zm`i$Smou(s3NzW>DhXSu{));9v#CrkYLY6~zn3W|yp*GLU(Z=2nA3aH+9}NH'
    'i-<!4UUlYBx@HP1d%0V84$UPQ)-+Y!!3WaPVR${)O8_f;HAfPj#{$XR4;^;QQdnVjc4*K@hfZOMgTpm-8&o8%j7mJS<}9{1tDX33'
    'DI4i%B&RUd$2}fNf25-#g|$AmYJtH%_Dv6KeG=X$=}&rDlISN<9whZi$b;lP4SB%(i1UDjKJ{O~K417RV4p8~Utk&uUled}x8#+f'
    '5n!HspO9F-+rmQMy2~}UK8*8p-Ewv?%w2ZwQY>2v+bk1GTCmO2`6PvDzS%9W-FkPsa6A42w)wjASYLr82`?QL_x<k<&bM8|x%KQ9'
    '_wT*$KDzg#d;clA_tx}}F8;@G@wrb&?!|jJab~JyFHZcSGIm4I(XGQ*$FnNCZZWjL&RfqNVE?V}(6ArZpOg~}l)<FTJ{~4z_VF+&'
    'vw!DZlLX@?xVIQRcFJb&Z!l#i7)z1wia`~e+dAJjrzaR_y*WLp%RRmiJD3CSjeShxy(Jizu}8p;=3dXzyZ<~0)kDVki(>%{K;LgL'
    '`uvQU@EDXClikl~#^eEM+yab7okB4n%@m5k*q=f%F2fXx!O2so_b|OniM|hip1r2nFK18ZshT8qb4~-9dmk24YtMma|HM7uX~0nU'
    'tau*tB<3=9i7}U%(1zTA``hVi@k5+|-LjkWx@r6oFQEO7BBd^@<d@#Z71-=9Z?-q?LmYuyx4n6%GoX>wZ_5|BTrIEHJJvh91dF>H'
    '=iP#K>%3=hGxxqhyI?;2gKmVgATW_%<2CjZ9IF@h@EBjPx3J=L4qbIcB;IRqcX!Tv4(@h3bKZT}dH-SO9f(c|Jkr>Wn5!T0{DuW*'
    'U*cxvy@~lXBw~-k?YvLn>i{FSq1O_1FHUdUYv)~zx%wDiV`#CL!KFRqXmoX4w^!mXJmhF}J?^eE`15W+W1@V()mXb3#n-TX>}p7R'
    'v8fY5;Bnl{gU=xiCVq#nEqfn#@+J(gv>E##t$YP9WF<t&pCrK-kyaCbM4L^Vl3nmhcEK(2Eho;&+<PZmX*=;yZdSoZk=7GG#qENp'
    '5^4m0WkpSvc&BA0Ehvu5+<Pu}n|bhEq}UI0UpDjGIX4_*QO7%233g<pdnMkDAzQ;U8U`f|ULCX#crx?lRX0y;?;mn!E*HD0_hn{t'
    'ce`2!6zZmR>wrLYmYXL_MxWN})tl*Rd*eM9a3Ze-oZX#wS3n03rcjnn;TXOFej9>S7{{FlCPHE`i=py*z>vP(Ew=N!#l1(h?$)cj'
    ')tXczZ;6LPGs$dzb@h;s<AE3UZI+!E;|nU;X3k%C<7#=?datJI*6Y=G;k~^s4JzJEcUy5sCd#|%+UKn>6Lt#LbJxwS?RK|bdSI<9'
    'lRYz7hLf)0Uu`jCu<LVX86^3ewsTiD+qHweXZMFZqR#y?x`Jt7woG{J3$?d*+xrdc1y*8C&SLO|*(2&EaG_M?-8(z_uiXYOsU;UI'
    'VrQ(`&2Flk+<fnuh56bu(Fk27)HAE3l?)4Rf%xN$)?Jf1l*ceJ3c+r=;d$i&JCDK!c50#6z|L6S+3qr6c4Bfti(@4Y1%r4I<jE+W'
    'umt#mNfOp-?QuLFGM#_TgO9O1Wkyh*GBE@h##2@R_cFtkfymh2V)eFNUbo%>g$jNCrPZ2SZoG3El&0J|(wTDEH|u5%?Lt}Poo(+t'
    'rssJA%B7Y!-FlzbOri319&_dUBIZgCr8VF3ePwyK^O=YIJX1bylxHwM=*#OFjwOwnuJ0{8@}~?g56-2sB&Wi#xUjs8oL2d?ikR|o'
    '9Wmwersqj;25?3#o3kjA9-A|PiyEdg$s&uGqOT&4xZU?%aPZB1d9>Wj$1MOOMmS=G;}(FQZwo*bxp<hG)aAyE6rN?1y$}~>q~Jtn'
    '=^n(3t(WomvOL1!V80?9E*mWABx=Mg@C8eDt}qer3>W~0Fl7LIcy~ak5-iwD|9Kw!yRcz~EP4nvZwrW4R(NYbAKipm8vuTJtX>$o'
    'fK<ZJdBltN2ZWXWtiJ%xCePOdW^ag*!T_$q?f_FdEN}R}=`EphFs8H72g1q`G~9=kr|Z?Lb}5~AFR~novwu@SZ-M?1SUFx_hhg<I'
    '6bEPVE(93b0EoU{WY*1D@ayNR05@auvRqhYkIdRF2m3+iJ?L~E;j0{(byH_lO1WpR!ef|o_kB0bt$AwW5Upd~xW$zZ&rlV4Y4b1+'
    'o!Sis9G)EoBsw1~W^;UY6tL*BzfB3Y-)~dG1i-sHFa<oZQ1c{O;+{ksm^l9Gt(s$Yh?dDQON1qEOci079P>qQnH)1mv`mf}<aitQ'
    'NBC`19B+m7aLguQ1szjLZv`EbOW2fw8Rj(F?@+`cKgU-A0>`Wq7Su8Ige7>)KfNV*%tUr47Y9@?{70CUo_DeO(g#t|&K?e-{8lfC'
    'pu*?nVCNS{Pkx^lhfOXLp)otZI9y`fKI?4);}EG0yA(3JCyc|Qwzt!vzX^;3qIt-pvU|cf3Yz!w=x+i`F%`Ak4KNoi!ybib2N*{~'
    'tFSF1A8ZKYP-qo0D0}<EI0gzkWiSn`;>8QUKaArYzk7`1oOrt!2RU}T7)Lnw;Uh+(r4wKh3OjSUDCecSyZXFquBqE@9uIW@I-*@%'
    'ssWCp@hYK>%QUQUxsPZH4P_kpP!hv9@~k9$apZ4l;F2U7v$!PHki{jL1}rYgHCk~=p`nWFhLQv-j=V+*R2(ucxWHNi6$de(woZ7B'
    'Qe2v7kmAx*gA|u$8lt!~*8s((g~lf?Ej2oEX{B+AOKS~FT&XdMt27*OwGTuZ4MaM*H574aqrr&FCK`^oEYX0(WvPZFF3U71aapcm'
    'iOUKNOk7rKXyUR;gA<q48lJeU(E!Ee6Ae*Zo@kKb@>IhVmuDKNxIEWT#pQ(tD=sfJTyc4&0gKCP4Ov{?Xwc${iH0q%NHlP9MXI5T'
    'D>4mUT#;+g;)+7U6<3r#N+~LhPFzuISmKJt2PNf1!xC2}8ko2;^`VI?GasC|GWX$$D+?c>xU%#iiYqH0q`0#7VTvmoAE>x$;zJcz'
    'B|cbjRqDePS7kn6aaHa^7Duz5MlG%?eB9z_^3%}8RizJJTvhq-#Z|QrU|iMs5XRMs4`N)M`Y^`TnGa-Ko%>M6HI)xyTvPiX#x+fd'
    'UPyr&sJOcEaf)juK1gv*<|7l=<UTBMP2!^w*Q7oWaVZ9}Y)-C=urrxvcfT*WF2jE0x(Yjy>pE;hZVDe}xTf^3vZJ<EC)p*iW9%fm'
    'gjLUDG+}k?FfF}z?5L5|F?Q6->J_^rNxetx5?D2MhFyYzF3S_t8~n;dl1{>+M3N?9MIwPklC_8gHi?~Gm%u8qtLqZjCH8V%0?Wki'
    'txI5=#H&qUo!F^$35*T9wJw3VVUN}&FgWbTx&$VNomiK^=&<+d5||xXQ%GQV*jIH4Oph!iBrra*f{?)cuxIKL7$8|MNMM54A9V?g'
    'knEC3V20QYbqNd+JE1OtDPsTAB``+pe!2wah#gRuz#y^n=@OVEc0FAJqr{G<OJJ7R<8%oO6FZwOfoWn_(<LxY>}a|K=7~K_m%u;?'
    'pr61*v3Kbb7%BEGT>>-3o~27*sMxP`2}~6`lrDj>Vt3LdFj4GDx&$_gy-1g!U$YPC5?CzuAYFnnC7^r)`z2s}0s|%>d;$w5@OuIi'
    'Ca8M?8z!z|0wX4lVgf5BZejv6CjMbkrolT*VARAhOkl{wFHB&(*fVqqtQUKQE`j+<#qEIoVvo=zup{gWI_lBt1-hhZybtIS*g5t9'
    'T{@X~*Uu%edV+qZFafDJAFzR`xF0ZrsW>38f~mM5Fh;33Ax-YRI+wsers9aeG^OH+zy_u2i&Wm5a|tXJyKydo@njFqC9t0Czd0H#'
    '-*?{HZaME<w3ZySBf&4bDC_XxA9s_<B^4-9oN%aiN4!S}9JX>cw38RX_HLmtscI4=3Wp@(O%z~cFy2QJf=dZ_M>Y)!3mG9MkbFoR'
    '5=;t*RR5U(vDld*1(0A*1ebkc>c)on38N#zxdcZd49S;NO}jfdJ2+vV3%dJx^l=N$dgZplfuZKzAjC*{-Z>UT_&CxtHQTYxE^*)t'
    '^bB@i&r>k{-Yv-irA6AOo^l*18`I2jq-=P)x^G34Na{WgI;}w7NVYSoC-6m7bK*#izZbmw3xT_NyNi5JZS{riRS7BY3oI=}b-=v!'
    '2LZ}Y1Sda<G)G{`$xu&};YnXlS77$^ggMJEEu#uN;hsdgqe`7bx=X1oP9oi<D0USzMeX`Wf%U%>RG;_p$P1Lmm&1x<>U%2a|5Mv-'
    'G26-RAIXE7|EcXf*$kXvu6UD!Mdo0J{7M!VzS?PyRM}^;((ufdj(PK$Eeo^avte17N1xdtI-|0l`7%hxQ(43~6%)i$<f(1o8I^cC'
    'Xy6%{gwtLF&q!;hw%KOLFWQzU1yQS?M(vqjf<?PwxEH_!(rr{CHFcp=qru6HhRbPGPpbLXvMTd+FddZJ*Pf#CX_u6cl*^xF0q0EC'
    'Z_cdd;Ub(_&BFmW8)_ad!&$FGQ{8B<mlQ`$aW1Pv=TR}#A<u0w@Fvb9tC$omc>SVN*bd%DCIwOJJ(txd+EXTMs?77K6y^*n14n>&'
    'tVs*hU=SQ3>Lyt(WL@hb>N-@Hi(%KHQE<`kI;5bBsO!)`yV%op;Llt{U8h7zktu+0a}k+QU>Sb96Z6nPFT&K8lvJHR%j(=WvN-px'
    'tj&F^{iUI|UdTe-i>T5xu3p5oV{hoCEa$zn?G4xHrEQ6dGI-gyk`*cKrD+E0WKLG=9M>kT;0-xAs6?hhDvfUAI7BA8l;^3^DbtzK'
    '8PmDaIn#yEm|-1<&3IlgT`65MT`OHN-7sC2{Jn@%CQ~LS`k1rx&n3GgRhq?1v^WG~j$>xfHPemKT)cjsur^XDE*ELiL}}JenkvoO'
    'Ni(In_%v6VwUZV~v-oMLG>e~BN{cwP(kyP;D9zQ;#(;O^I2b3o;_NbQ%!;$iv@t8rF4ONT$xa)y;+~UfV^*yFOdGS3@>IL%mySbq'
    '(5${pwOd_**6b(zdamNutleD2ty#Odid(aGa}~E{?dF<a&DzaX+?utUtGG3*BUf>2R!6Sl)~t?P#jRN#n%#tJQ+RP%JB1gQwNrR;'
    'Sv!Rnm#bTNaV0-5E^DVyaT``gq2e~IjzYz4SRI9m+ps$H^9g5Hs<;hnrxbA$`MgwdoqV3@b9p~knzdP~xD9Kk^x|^$OD`^0zx3jA'
    '^-C`<S6^RGxOSBnm&LDCyN<O{d2!`^)vn{}RH|La;#VrJWAQ5$*Kud4w0y^%p;B=jcZN#EbzEJ2oN#fqitD)cwHKFbTYGW2I<<;B'
    'mG4#DDQmx0ai=V9t>R8uoLa@5a_6g6o~e|t;!aunN+z6rqvB3kyhg>Ha$__qZo}C(Ub{kjaantf7nilu_|CxMHeOtAjmC@1+HSmd'
    'A+DB=2-d09t*{{AQa?vwvB{-=j+!P+`_D6`Rd_g(F7<O%A=#_&rR3+$8o#gEV-dosjjs^2IW_SW79gBj_zLcoOa1f*y{LV!5Hh;d'
    '_jxp0>iZNcL3M)2%6Z!kC3w>ggwT1*p7K+b5h$Vab{$@_^JX1Lp;N0~PWWY&5on?FHXR|9^Cmro$lju-5INVJph$1eQ*<(K&QpHs'
    'WyFZ^#vC!8^R^twr1Pd6*rfB89O$I;h8*~$^L88vrSoPSftvGHoGFzNn5FYJ9H^!9CLEER^A<dVF1!IptmeG^&Y%l#z7gR$Z@n|r'
    '-W%@>wfD9gn5gsJ1fP1#jR?@G;jVy^I&ZfT?>RNw6_8S=R=Yxs=e*GdTI#&bMr7!`$p&KTyu}7)>b$|uQG4HaQ6F!vbLc{?b%8kE'
    'd1IZULTalEw&mVb=lrtD2td}Up)S}`s+}&_u&J3Y0Ejtnr4d*;KcJAY+T>z}+Io|W;LLf841CskgN!K4d3#)PR^CKFMsJM~NjPte'
    'fs;CKi`i@QLk5-imY7{QZ-`4&&)eY=it}a|L5%ZOxP;QZ5e5kBybT5n>%0jr_+^!`;DWs3P>_vMT2wIt7E!H1u-2mT=1VsAz38n4'
    '(`Sx$vawtXwcs!T`x`up4G_s@J_aJ0r8{a55B@dL*h<TI9xK~#7zZ<B3m0}p3m3YLK~0EocPH6h)i|GFk5zCfJZ=p5+2TWgGQ~Pn'
    'cGEobXO@rMJHpQlKZu_I%!~KW%Y)QB*xe~N@!XJi<MY;I9$dk;Qobp$@det_8ef_(s_{k1ffC6SjcqoW9v=K}<tQri|G<zv&4&m7'
    '-jFz~z>4O{mL&KeNEk?`r5a6TOKRBm+CBV7FbHP(zmy6AGAxVkmX`+3l_mB6o292)eJ!(W+F&mH)bh7?%1)H63j97|gnZkGZ!(@m'
    '4?@nD!q<JjhX?;N=7hW_@q^GjSMdX%dE15uD)|5Eu|oFK-jkqH*LxDAZ}7xhm=s7|*pbLB3r}6POfq~8&*)Ni9bZN(1{FBoLZp|%'
    'ut%4;v%<r^jMfKc;6#fH7!WZFu6V#*CWt&PJ&4F9#wVJ%_cq}Pw(ASG5Uw?<DdsgCiZeh4?~Fg}{{2oi`BO^L1`E0>FZp#n8!KiC'
    'CHc*pB7I|-I29wUA3wkmBhDPKo8MF_+0ek5$@XvAVJwX`@f_M@EKC{^vq<?@;Mm0(yu*7vMf1qYFV}P<7^TW-L4yGG<{rdyvLTB('
    'SJV`8PUG<4UxJ9xv=o)}XV3+lPnc&c5|+7I+3em%^CxA{Mhiw$a0c@yjgPiJUE<xrf)R<`M$;x$t(EpfS`M7adKR-}2e{~-G}Ojx'
    'Oc_`+#mu|dDhEeS+ev1q>(ai3@8Y#7R67DyG17Ft{I8t$hZQ+%0BOcDqn>{G3Z_d=;T#_Pb5HmQt!rXrU{2+W$RyyEoItqZcD$Ox'
    'ZNQ<G!vm7-YM~EOP}o$@)xj)>vo41Rq!NFyl@$PQ`&!O5T$=?n#PiqD0vd^My=MUpZ-zaaf)V3wJsv2PshEc>{}0l92IlbKzXi%V'
    'Ccqctjo6~DseNGW!Bn4wz5HBN#6rEj?ec^=@Qobl;Iq00ogKpSDFATU_I-Hp4;?X=V<7Wr1kr2r;dr5;Ht&xY($_p188kV}<K;lA'
    'n?H#xE(LPa^KjxdP7QDB9mK?N!|YZVuFP!RyA$F1v#F9ZDRCYzNJ8?kAPFetFLD^>l^lh6Wfmj>{k+<<bV%J}Atz=Q(SoD{$1F&q'
    'l^4;1WDCwPS5hNRVI3a)7fD84j7EStFDmt{0+;ssORu{O+|^oNt-<6oo)XkS-e?h&hT*N80kUm60kFo~|D{1wVMz76{t3=bJ9q)g'
    '%*@?rBXO5<uxJ^rrc(8m(Q0Z9&TuuA%qmVm93D^;n!~>`e3fgpH({O}BxWXX?4@;X;Xp2RX%66>Id*t>@Gm;XN=`$q>=1&Zx*7~2'
    'xVfv|5W1oYto$k?zBC;*#iHEG4l%g9t9?tiB=0I-x}AZgOShe$)F{I*v_XJqF?UL>yMj&=PT?ekwB(FgdR{`fm(2C2Foccb%sCb5'
    'K91Spe1^OZzFkGWqIO?JtwKHNPL7_110#|_$xJ!Od3f+|E$!WA*f@KzSlE}A9X#@>veo|nyND6I@jBuMYgI-3;E9X0{u%=5vedwO'
    'fc5a;Uok}|NDmMGqbK~C7^!*1Pt0{7oEso`dy-6sCyjx-;6Im4`d)#r{8PNl-t&KuWElNj;nYp^1iVz@ido?hzYMd~@Z}Z&d6LN!'
    'e^Y~)7BrUM5rEA)f0YA={s8LX!GAZTaZ%8h{psP3cVK87*%PO#HGDGx10If#v&n;*KCo}s%8XuZlp78c$`cnoA@;xNIBPjYxsG-q'
    '6yWf+0-_ohSfLl=y=X&31I}<m1ofHdP6cU+((vOp;xGJJF&WOS;o4xPwtO4QKyJV50=ww~kdxx^M$V6JA|23B+(i2$5^&;O7+2s8'
    'cVUno<N^^H1sQX^v(Qzh0!vRsA0GT?(68Y&;hEXSfrw8o{t-?J4&Up-O2cGMC$tX_NU>_({u8Bf4CL_OpK)4@oGifmBZVRu%F_F+'
    'WRyW4{vHMC6{M1_9J<~5y(QRnxQ%pIfHT}%LM4U!holxcGlR=iE5jQN6l}Jj09oM!?1u-Lru`v08KM5A{^Wr#g6U7O7bTnomCZ=0'
    'W!m27q6fD7k=E#l{oz5%seZ}C-pOI*T{N{*rn}+PPC4%SQ#*;fi>7YsfV+KLXGn9qc<T(Z3@5@55B>=Z<JLN6$hB$GBdF)>;vF}n'
    '$6XX0B7ol6-8D31Udy5EH*zG~-Wns@rKrunlXKeNsYyl)-piTo`$%16B=7rrp|b8<Kj27~w{p(=ZL|l6D)=_qgF_{~9qhp&MdK!g'
    '!-ENup_7($6zk1=w!OihpLo&*m2>i1u+6ueOn93wC!}m9B#LChHaK%aotTzpW<nd1DQyg<Sm~UW&JE%-`F*0lRvO)oD}-7*ke}<X'
    'eMdLkGQr>t(puSLoBgr<^mtI&<6dR$mRe@m+8;-?KaOgT&9R)qzE~uGFTY>tuT_1#`4y}`$nS~%+Nzukq(A9Nf6|x!#7ch>Nq-Va'
    '|3~@#Qh$fCJ=I?;(^IS7r+Yq<DFMV+^7~AGZBEZ@PS1upJ+nRPRDZS2Pi<DG14W(o6m@F#(%UP_yhvB4wic&Wkgw(UPx5=FzgC_z'
    'TeY)c)z0<Tespd>I*-T2`7n>?`fERXzUMuj!;rqvUt8|QKzSEE<y~0iUF=cbMWnoosH0sNBk^bX{YHMjmERZoYvp>;lj5cR+LvD1'
    '+Q00N234Q4pEx@t-JtT(t345%e_%D@qS~9qM5ZHcIHQedK`U@<Zwm`rO!|u1m!|p~)~tkHYbvZq1zNm%&+rRCmJ`1e^k$Y=n3mNQ'
    '5SRLEb!i*wGA5#~-lu$H4q8f_T1f*r4e6*Km?aCQ{n7(SZ7N-LFa!cErmf5~J0<A~0~2wN(KQ1mWVt|yxUYtl0+9MmYjxOK8QOtD'
    '+Fs#pzl_#)+tw%~0Q^iwJz8OXCYF|n`nJGQoc5EWqV9&^kQR(9{hj-S7w~G~6O5-b0Vti59!dwP<LcUW)azkyuuwTOj8;4%ZYf){'
    '9vB|;Y$xkM;4#m>sG8biSQX+1p(>i&E-@eUf_bkO%x(4NQOnMw_WO(cD*bAxI#t5Lim<S~a<S(lV81?Tm1zN9VF--Nlr?AChoTw?'
    'a>MDJPbfAEQr}%#p_f+Z<xprw_&DhiS0=6PwIC`O>IklEVXHwSt$K~L@~_$!S=pvr?dcz@NEs_HvWGd9@(8CgLX^lHi)$*!K$^_5'
    '&9Sm-xYOT&VJfZgWuR@}j}SxVC|IZzz(PX=uuz!+4rI>4cL@XTf&Q!hdaNxXjbREfTSPM66|qe9de~av_1_u1V8FB<Q#smFYum9r'
    'gvONZ)9YcMwqO@Cf-|BT+Su$jHp5LkGjE3Zd+<ppk2?wd+M6;UNSrcVN)RMYd%%dvfD3`vBDYq;?NFqx@qPuo3F!dd1YU1k*iLTH'
    '8m8Z@LaO(jnxdUm=WbvIc0Dt&vjcv&XTa~G0dFA{W<=&=XWI9*{JxQ2l|YT;y%qGnC)T}hxVQRiUw>;G;cegPU@)Uge*Zg#EdJrM'
    ')nYc{79(yk;ua%rG2#{@ZZYB(BW^L`79(yk;ua%rG2#{@ZZYB(BX04j;ufdV#k?DMBYZK!7bAQz!WScaF~S!kd@;foBYZK!7bAQz'
    '!WScaF~S!kd@;fopCWuQLKh=+F+vw3bTL8~BXluB7bA2rLKh=+F+vw3bTL8~BXluB7bA4>2|^ctXcw>BZP#TLv?wbEEs{xuT7a$7'
    'IEYAf;20S}tLi{_HG%S40VP^NTHBY1&*b;X!C{rA0kvR4>L`Q`1(2WXuYE^R3nm1$NK!^EsF-70S&v#U(XZ@rud)$p0fw#paa8-`'
    'sP;fDAQPh&MNu+pkt9GZs;UmC1ryPz0_zWw#mT{8O0=RDOjzle6Qmb9NY4zBo(YwnDU}}7A3K2+wV>McPzz!`l{zVE!Gx$+2>TJU'
    '#0-J>>fo@>GN2Zy<ult4p4m2zQ43~Cj{<Qj`a1PJTwx1lTTL-1Xo_i33=^?EV4f<ADX9h%DhUx^i+27b^qEL_X6trl>vlG*+qq<N'
    'ZhP*z?YRcFU~<qr&!ww**n)}ZJ+Q=Z(>E7V{)H7bf-RV1lm}Xs2coAu@VxRsX-{K{tpw747CF8-IBfEqVGE*P=&#ksi{4OuDHZat'
    '1qfUF2(}=GlaA<Y7gpGU30ryL;MI&eu7NH1S@)o>n*dudS8Fd+fGtRD4_ok4)&{37Y>}5u3|ka+ZefcI#crwlCq=+5kkM3s18#vq'
    '4pbp6W85Ok@))=943Asz#}RHJEGQ1DF}MYnAh<<VFm6#;+@dhJ1-@3?qKI*eBEl{B&0t$>Q}Hu)iXfZd79s8JViDsORaRNt0y)q0'
    'S8xkMz;k6<yIP(F+=8D7Zjr~h1!Pp*0?nzo1%DMfE5GS+3sgcIx3zt@wdS`S^xd}CUoCFI4BKx7x8StLE!e!aQJ+@eLY@h7!H=Tu'
    'E#Vz13*>^if?ROD403^bU&#YPE{cF$;7dX-3X5DY7sv%CJ#vxIVAG*>ZO8caaGHvc3$hfV7YO8$3sfUUE{ePvAQzlt54rG6gIsX#'
    'J>&vR)l_U-`H>(OAgFVYA)Q-4VLtE^<~=`QZry@;<Q9130{Q+$eqV{&W8|U`<N~iKa>0c3%d~0w$OS(KashoB<O0gH$OXTk$VFZy'
    '0l7dnx8hJ}4WJVVOYtos7f@tCF2L8Gv$TV0X$RAC*hx5s=cGq2AoJ2%UyEFTq0ZpS7PcA;)>Ut?5^{lAQCkGHTiFrYLoS#XjntJF'
    '*&`P<*>{UvC?iB#T#`jDvTA@_WMyHH3mP;ltA;!M4ah}7rq&=AD8?ce$_U6sUX=#9z+9`y1-fe=xlm?6F4#sfbb+=v&;{tfil70y'
    'h)97hsD1&u$cmy5T|o92x`<e|iUztsKeo_CU>NA4$Lu&slK{FverxNbc<3T8vH)H1qo`9e%Rm>H3fUpSvyBY#jh(hPcB<aQQ}t$O'
    '9z1jbr5fl0EhW$eKbz}Fus(}G7o7Ic1-~|gF7TQ{7g<vEp$mS_9x(C{=pv*8bb(>fgD#*J>E)ab&;@riU>BU7#V+u&8l#;x1iOJD'
    '*!2v-&JOwAo*}=BhP=ftm=R6MJL7S_mPUFb{`hx7-|Me!c!OOO9=kv`Z-w*LzW&zs6N_CG0lVnFw%CQe?*j4+0Ssnq6b)h!t{nBk'
    'l_MLj97UnYQ52dSnb73OhMS)$JTU?opE7_!0)Ht2d^wD=pGsYx+JNz?4H%ye!{w)Tf*S#h5y1E@0~o0Ddjc4OSG*g*XsSK<1!}t='
    'zo>io1?3ar7s~MXg#Z*5zYx}b{G#56UjT8iYTt`r;6ZSTK>kqtLef7DzkmYY3%{r=e!-uO_{Br`1@xo%1**9Zzu@1wyxzkvnD^fJ'
    '1;Y`#WCLPo6F))x0%E)megV|sC%`X=`iuN(d%hY*^$U4rVMS2<A|LL&;O8HNUo^SFFDRQ^vA&Pu7f|F7zW{q_r;eqaI+nvu@^1Ws'
    'U)zIUaCmPEi+5gtW2QIIkKz~nN^c<+Jny1{`X%rS5O?}(@C(5+eh7X+ZT^$v7lKastrwQui(lkb-p4PB;ns^{&(@2gxAg)7NBD(j'
    'So|Vp5+|z}zaW)({DKL=FVHnTet}0ZegW1y@CyJ1cFNh<DQ6Q;)tjMtco4tf5<W71!I*-r@^%Q>=++Br(w`f@K%qNp2zCQQu<IFu'
    'ogMPKJwtvM4f%)h3w|uS3@H6t-gqOii#CAzLHD-d?|aU~PlR8@het*jV}vnA7-NJnMi^s+F-90;gfT`KV}vnA7-NJnMi^s+F-90;'
    'gfTuz7^8Rp#dwrtgfPaVBqM||LKx#wlJO|Xc$8#3N-`cL8IO{TM@hz`B;!$%@hHi7l;jgSN^*XGJ6$aRTrBQxH1_|j-D<S+<YvAv'
    '-0%F8h4=N3w=N35D{}L`aB>e?r~H%7HF&kfZCQ0m;qO*m$}ipBoqqh(-A-pt-uY@LCg<5s<IdamnqDmtA<j*Z^EG5FyX?N6%L`wV'
    '?^ZRPr8x6tGkK$Z<a~Zj0v1h|!*jRuAsXsl<z4#1*Rq*-D(T3SZVaSlp1jNPB`XUt&Y~q-Tc;GSus+KyiI-Ao6gajckQ8aLS!pA*'
    '8Z0pG?(j0n(52U_@9gyF*6Y=q>1qp)Fi(X+mT?bHZxzY{i%V|mDzK#Rh_}0ozU$@F4eI$@8bdq|!Ru!{$TiOLbvJMDWi(j`wK@}X'
    'Bb}C`8>FCbR34!deFeDP1Xg*pSUlbK-?*L6`mF7p<%qN)A28yK!0P1$UX<0|)o7I}tK+v2PW5<{o8`qT*@4y156pgsUOr|@pqQ5&'
    '6Rzj3^Tyk5v{3UF6u!~Wg09I_c22eT<<NPV$rC&?7P~1KfCnN%j{la|>m8dTWUTREH$XPh&jYX1=#?<z(2lJU)I6KJ+Z6^^VWT|C'
    'yt94WiBNQF)-t+Azhx9C$@axucia07=>~(jRZEa(O^B>=PS0O=<9>OmMY1`VWP|l$n(LS3Udf9RTSXyNxL2@<?-k^bifw8xQBpT4'
    '_zHwT2~p87P`YWm$yHP|UtV>-<@R2_op&BwmmO9_^FUIEf-P1C#;0XaNAirdcQ?=z=4|B2g1urR&mo2wc_ug%(d3>`MD9|{;@AXI'
    '3xhAZ%KGcA>Sa=1lty@zR}z*~aae*lf+GyQW-sa;{g7j|-R!359sHQGO#4fyd@CO2Ea(X7L_S&R1cnS(zUaLkdSop;#}94K@#A`*'
    'UoVU}pV&qOmd)wGMNMR^0YSkR;N7*$&I8`@<)UOj?qEPjIbAA|rn*z3BB6mMZKHJ)-E4QM1F)lL3bk5S7X247S8M8q)LP8KO{R4e'
    'W#kmw^%fkNYSj;0x8xQ^B`PZ_QJr{Wy*$epuQmJ*DySPKFjg4F4>{$0HQlxMppZ_){%q#AbH=Wa-&{rB=erktn;kH78v2{v<<0hn'
    ';4;oC`0=RCmK-5G+1_;a;|iW^U1If-=iM}sbRy1;y7AG)bfOK?df>4->c+e3{hQ;25sXNeeod;?w%n;5#t44Xc3$zO%b%<W9E<Pf'
    ')Jrq(<FdOe6Gi9lKA+#Vn@{=F^lxyjPA{wfp=)(mNE0yr#BL;r*6NsJfMBK#-V26ejvzdw1<FG}M47cZ2=L`lwx_ygXVv@Es`u%h'
    '1wO@ci1<ptr@yzgI%?q`yH>}cn+@X6Ep&JuZ|pc9B8ks+&Ca&S^F3>NX1B#BuvUlPZ?qM^6~+twwSv9qiSbew?QDm9X{-OTKbjR('
    'au!wai*<wR>I-vS{a~?9udC-x#EPdx*VPxj>+0cJgvB~@U41dQuD+;~-eO%ET~}Y|b@feVuB$KPy81`f>eAj?T|YL=9*ywcXTNc}'
    'XRQvNiLTWNF<h(T2fnW}xo@qme_j29`;CjqyVmORc&$#ZtB=>}de_w#(RKAz`XOs|mAS6I=v`O;z*-&D(OMn0R&UW-9dknALWeS#'
    'A>EdVD2jYwt&ZQ^zg8DrSkEs?bW!Pr^@Y8#{@weHdHv1ClYY_e{Q^s2U)v#mJw%l4S{<*d?Om&@ChxUYx9`IGV$X&3A7`!ZC*E(2'
    'az1pwF>J}h`;Du~JJ#x|$vgKOKe$#`P4=(VRg)jLRu^Ab|Bkgfxv;*l7uFYp3+s#Ch4qDASdY17|61Li3+s#M!urBrSYJdJ)&s@1'
    'Yjw&nD+_}Q>$Bm7^;u>vtS{_^^@UtmKUk~FCqHh#v8=oGV)J;hu9!TwSXaeY)`Q-&SU0?~zKE}^FNTYCAGqN-EZz-P^UPvhkE!Eq'
    '?L&SuDeT{H%#Wg8%`CfEmk$=}5FKo67_zb3dBb9zkb@1)VX>}vWqq{a*k4)yc)%YP>mInWKH6}cC*@-sj-$o8Jy+IaT=W;~%$4<z'
    'E!GY0tk2}m`k#BTF1oY+r&z3$JL}Px-r8>X)^@zNeb2)K84-GMvUQ93Wq-dhg2qo~yD|S-X`a}a<4L@$^6vt|pod?`qc1Fa^u;ii'
    '{S+XKN46V(gcH+Pz5OT<27a}JpW3WW2SNC0FZw;TLHOyOApA56!aafk!U|#$4B!)@tTWpO&ukw&8*27rAs9boxA7-}VCZgR^b5P&'
    'nB;q5d)kZML6Q&LZTt%Y7`)2=o&ZMG`+IxB7yuY`mhJ&CdVg>45db5vdjLjWj{t_nEZzlROlkvQOeQ0M@!kLi4fzPbAjU5aV3@zS'
    'Hv$;p!1N=VjUNUu>h#9|80DmV7k~kix(~p>xBFK0M*!mk0F1OO2LQ(8od8DfFYZ0OmEnC4Oz+!U@G<a<_)qTrn(&K{dSLojk6*-_'
    'jmz@U&Bo?W?)`T03ry2*#O*ft1^D;Y*SPOF6A^xawtj2-$y?h`-uA=NA$}2K7v!uHc7dqi$U68(_U@CT!D;iOUXXBPPn#b_C(Dnb'
    'gXBl%Ao-EK`QbD9{TZ+e?3%WfJ+{%z@u0HDy~-Z<<DFw$`{Stg$5HLyx&7jOu?smWjlpqZL#LC0yMEGhjZgX>@QL-pPNGTvB$^ce'
    'C|&YHk4o>sE*?E9jU1oZe(=opgJ;9ypIJ2Qlg2KHKC^xB%qr<@h$oy&Z#lQ_&AB~la2_8?IUhQa&lSV4F4*%u7{@1uU635#NWb`2'
    'VG5D;h3#oCdN%!~{@Ryb+S<SD9}N8|unXSR@zJr19FT~`F7jmm=8JUlgRl#_8_w?MpG<li^OX^>3v>Njd?Va`>;fhHYOo7z(EkzG'
    'ML|OTVC<qKCH)$(3wRIvp$mTWPUHereV?rtf?Vu9Chd`nAF`+aqaqim#?OXa&<CFoa)I`IHC(!V9JzS(syFEKQRD(I>^~;0$OVo|'
    '??W!=TOb#ciA65J*PgSqv%u2Mw##8Bc@N|Q&psk@ftlr#KrX5wa*_OC<RZ;}<T2?ViCm!V4RQhcLy(I+oeYo*-n|ha7nWtOOZXVb'
    'MUuY@xrmQRzYlUj6XD+xaslSghFmoDdjJ>swRT`PumiiE9oX3szuPn7chQJ{1h@cYyv;qp1!EGw0B~{E*{x;&+(?95{Nl$(etWnD'
    'jMc9Jw?L=*$#1Fu_<Jsp<u8a^pn-pFdoJ+JCv<8=Z+QD*hem$*o(q^=XKk|L7EBC+zXxy&e%8k=m>WfT58@X5l(oU>$8UIh5VuGI'
    'Zh?Fr$1Nt42ks&0UnuawdoCuw?4FA~$N7I!+@k)VJr`yE8`^VG=D(stBM<MnDD&Sga`9n%F7ihYjg;@Y;H}KxiCjFi=K|mEK`y}m'
    'wICOt&Yp{pfm|Sz{w0wMw7uPPQRe%Q3z)7Lxe%5|E+%y!xrpA7snxP{cJ;g;hg>8yOMmPO-hNKxV$WR?9~-$y%MrPF2XgTV92t4('
    '?yf%XgqphThM)_&wWFa+eq1u4d(Bd$D2cnsk_lZ<lQB1yWuq>cg=F4kK*p&{7L-hoEY(#{CYAK{E?I|UL)WI!;$}h;Fq1_<w!|&y'
    'ezq=|(!|5BR&w`Rm!!NJ6qYo48ydaZ&}AiEYC_kIpblvgl4(e0A(@9{5t3y{Rv}r3WaE>W-oBP(q1-H#n}u?-P;M5=%|f|ZC^rk`'
    'W})0Hl-p%c7tm53%FRQ$c_=pz<>sN>Jd~S<a`RAb9?H!_xuK<tP;L>*Eke0PD7OgZ7NOiClv{*yi%@P6$}OpVGo&VTa}4@Qnb2g#'
    '&#42X%*}8gH~LMPlY!<pitq;ImN2&>F8XU(Q<AxjPtx-oimoPd9c7oKf-8tqrF1b7znb|HDhv)}TNQfaKvJO=&|Xzh?8!OQgspJ0'
    'p&}r8?T2Sg<?@iK>8hQEpHsQ=Lgq(TP37kNLP4KF@|wz(94aaSBGk37MBR8TkjlAZH4_p6**1w+SVIk*b29VNHq^isvTdkbZnUNh'
    '?^fZ3I=s+m)u{POdQ8K&Mh#L}qlS}-);1+;)JPH)Pmv@6iU!GoY#t{|I@3s1fGOZtsRCRS4PMAZcA%^vM<EwTI#>Z{6-I#broLIA'
    '>_#p%a+%CYE*O9?{xSSvp)mUCLL!I3j}A;@zeY!;q0g5^^2n#cXyDgCBWT?7Q~ETahxtS=$Dl#anb4T$w$0HK@sz%R!N!1R9-0NY'
    'R4N`uJ0<}d>?I6vp^{*z!w_SnV}igy#|IeaP!ERrgw%*pKEZo5A=G$}3Y(C4G{kGn0W`vET%BLa&R<tfwAeE7sZ=wj!Cm6!NE+JQ'
    'J7{E={9dW8QbLV*ua+yLT-oT%QBizLGF2#y%BLYM4^tf%Ri<5q#xr*x8qQo>8qGB{K!aIQ-gs5$AXK4R?p$^?uI-|SG<XwEW#lg5'
    'DVZv$qV^rQ_WhT}Z3^Q<!&Xua-4{Sl8|uiE35{7{B@#|J8nKef<UU?U<5g0H{ILN?qg7HB<wEtLu_~!XT!U~I@b}+;|Nj9|YbF%'
)
_TABLES = json.loads(zlib.decompress(base64.b85decode(_DATA)))
GLYPH_WIDTHS = _TABLES["widths"]
GLYPH_UNICODE = _TABLES["unicode"]
ENCODINGS = {name: {int(code): glyph for code, glyph in table.items()}
             for name, table in _TABLES["encodings"].items()}
del _TABLES, _DATA
