"""로컬 Adobe AFM에서 폭·내장 인코딩 데이터를 재현 가능하게 생성한다.

실행: python -m scripts.generate_pdf_core14 AFM_DIR --output MODULE --notice NOTICE
fontTools는 로컬 생성 시에만 Adobe Glyph List를 읽는 데 사용한다.
생성된 모듈과 dochan의 런타임에는 fontTools 의존성이 없다.
"""
import argparse
import base64
import hashlib
import importlib.metadata
import json
import re
import textwrap
import zlib
from pathlib import Path


NOTICE_MARKER = "Adobe Core 14 AFM metrics and Adobe Glyph List"


def generate(directory):
    from fontTools import agl

    metrics, encodings, unicode_map, notices, hashes = {}, {}, {}, set(), {}
    files = sorted(directory.glob("*.afm"))
    if len(files) != 14:
        raise ValueError("Core 14 AFM 파일 14개가 필요합니다")
    for path in files:
        raw = path.read_bytes()
        source = raw.decode("latin-1")
        font = re.search(r"^FontName (.+)$", source, re.M).group(1)
        widths, encoding = {}, {}
        for line in source.splitlines():
            if line.startswith("Notice ") or (line.startswith("Comment ") and "Copyright" in line):
                notices.add(line.split(" ", 1)[1])
            if not line.startswith("C "):
                continue
            fields = dict(part.strip().split(" ", 1) for part in line.split(";") if part.strip())
            glyph, code = fields["N"], int(fields["C"])
            widths[glyph] = int(fields["WX"])
            if 0 <= code <= 255:
                encoding[code] = glyph
            value = agl.toUnicode(glyph, isZapfDingbats=(font == "ZapfDingbats"))
            if value:
                unicode_map[glyph] = value
        metrics[font] = widths
        if font in ("Symbol", "ZapfDingbats"):
            encodings[font + "Encoding"] = encoding
        elif font == "Times-Roman":
            encodings["StandardEncoding"] = encoding
        hashes[path.name] = hashlib.sha256(raw).hexdigest()
    # ISO 32000-1 Annex D: these byte encodings use the same Unicode repertoire
    # as Python's codecs, with the PDF-specific space/hyphen/bullet exceptions.
    reverse = {value: glyph for glyph, value in sorted(unicode_map.items())}
    for name, codec in (("WinAnsiEncoding", "cp1252"), ("MacRomanEncoding", "mac_roman")):
        encoding = {}
        for code in range(32, 256):
            value = bytes([code]).decode(codec, errors="replace")
            glyph = reverse.get(value)
            if glyph:
                encoding[code] = glyph
        if name == "WinAnsiEncoding":
            encoding.update({160: "space", 173: "hyphen"})
            for code in (127, 129, 141, 143, 144, 157):
                encoding[code] = "bullet"
        else:
            encoding.update({202: "space", 219: "currency"})
            # Annex D's PDF MacRoman is not the modern Macintosh codec:
            # the Apple logo and these mathematical symbols are undefined.
            for code in (173, 176, 178, 179, 182, 183, 184, 185, 186, 195,
                         197, 198, 215, 240):
                encoding.pop(code, None)
        encodings[name] = encoding
    html = (directory / "MustRead.html").read_text(encoding="latin-1")
    paragraph = re.search(r"This file and the 14 PostScript.*?AFM files\.", html, re.S).group(0)
    # Retain the source AGL redistribution notice, including its disclaimer.
    agl_notice = agl._aglText.split("# Name:", 1)[0]
    agl_notice = "\n".join(line.removeprefix("# ").removeprefix("#") for line in agl_notice.splitlines()
                            if not line.startswith("# ---")).strip()
    fonttools_license = importlib.metadata.distribution("fonttools").read_text("licenses/LICENSE")
    if not fonttools_license:
        raise ValueError("FontTools ZapfDingbats 대응표의 MIT 고지를 찾지 못했습니다")
    notice = (NOTICE_MARKER + "\n\n" + "\n".join(sorted(notices)) + "\n\n" + paragraph
              + "\n\nAFM 에서 폭만 추출한 수정본입니다. 내장 인코딩 코드도 추출하고, "
              "Adobe Glyph List를 이용해 유니코드 대응표를 추가했습니다. 원본 AFM은 배포하지 않습니다.\n\n"
              + agl_notice + "\n\nFontTools ZapfDingbats Unicode mapping:\n\n" + fonttools_license)
    payload = json.dumps({"widths": metrics, "encodings": encodings, "unicode": unicode_map},
                         sort_keys=True, separators=(",", ":"), ensure_ascii=True).encode()
    compressed = base64.b85encode(zlib.compress(payload, 9)).decode()
    header = "\n".join("# " + line if line else "#" for line in notice.splitlines())
    module = (header + '\n\n"""Generated by scripts/generate_pdf_core14.py; do not edit by hand."""\n'
              + "import base64\nimport json\nimport zlib\n\n"
              + "SOURCE_SHA256 = " + repr(hashes) + "\n\n_DATA = (\n"
              + "\n".join("    " + repr(line) for line in textwrap.wrap(compressed, 100, break_on_hyphens=False))
              + "\n)\n_TABLES = json.loads(zlib.decompress(base64.b85decode(_DATA)))\n"
              + 'GLYPH_WIDTHS = _TABLES["widths"]\nGLYPH_UNICODE = _TABLES["unicode"]\n'
              + 'ENCODINGS = {name: {int(code): glyph for code, glyph in table.items()}\n'
              + '             for name, table in _TABLES["encodings"].items()}\n'
              + "del _TABLES, _DATA\n")
    return module, notice


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("afm_dir", type=Path)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--notice", type=Path)
    args = parser.parse_args()
    module, notice = generate(args.afm_dir)
    args.output.write_text(module, encoding="utf-8")
    if args.notice:
        existing = args.notice.read_text(encoding="utf-8") if args.notice.exists() else ""
        if NOTICE_MARKER not in existing:
            args.notice.write_text(existing.rstrip() + "\n\n" + notice, encoding="utf-8")


if __name__ == "__main__":
    main()
